### PR TITLE
Added Tel to phone

### PR DESCRIPTION
**Pull request by 1stdevfriend**
Congrats! 
This will allow the mobile user to call on the number with mere touch on the href link. Glad if this helped.

### CODE REVIEW

**Comment by MohammedAbidNafi** [comment]
I have checked this and approve this pull request

**Comment by 1stdevfriend** [comment]
??

**Comment by 1stdevfriend** [comment]
@vinitshahdeo no response?

**Comment by 1stdevfriend** [comment]
@vinitshahdeo Can you please look into this? I know you might have been going through a lot but just minor changes these are.

**Pull request closed without merging**
